"""Presentation layout for the three application pages."""
from PySide6.QtCore import QSize, Qt
from PySide6.QtWidgets import (
    QAbstractItemView, QCheckBox, QComboBox, QDoubleSpinBox, QFrame,
    QHBoxLayout, QHeaderView, QLineEdit, QProgressBar, QScrollArea,
    QSizePolicy, QSpinBox, QStackedWidget, QTableWidget, QVBoxLayout, QWidget,
)
from .appearance import badge, button, card, divider, icon, label, symbol_label


PAGE_TITLES = (
    ("识别工作台", "识别短语，查看文字，并合成播报。"),
    ("短语库", "把常用的话，加入你的识别列表。"),
    ("设置", "调整识别与播报，找到适合你的使用方式。"),
)


def table(columns):
    widget = QTableWidget(0, len(columns))
    widget.setHorizontalHeaderLabels(columns)
    widget.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
    widget.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
    widget.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
    widget.setShowGrid(False)
    widget.setAlternatingRowColors(False)
    widget.setWordWrap(False)
    widget.verticalHeader().hide()
    widget.verticalHeader().setDefaultSectionSize(48)
    widget.horizontalHeader().setHighlightSections(False)
    widget.horizontalHeader().setDefaultAlignment(Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter)
    widget.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
    widget.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)
    widget.setVerticalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)
    return widget


def empty_state(title, description, symbol="history"):
    widget = QWidget()
    layout = QVBoxLayout(widget)
    layout.setContentsMargins(20, 18, 20, 18)
    layout.setSpacing(10)
    layout.addStretch()
    layout.addWidget(symbol_label(symbol, 30, "#afbdd4"))
    for text, name in ((title, "emptyTitle"), (description, "subtle")):
        line = label(text, name, True)
        line.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(line)
    layout.addStretch()
    return widget


def scroll_page(body):
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    scroll.setFrameShape(QFrame.Shape.NoFrame)
    scroll.setWidget(body)
    return scroll


class WorkspaceLayout:
    def build_window(self):
        shell = QWidget()
        shell.setObjectName("shell")
        self.setCentralWidget(shell)
        outer = QHBoxLayout(shell)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(0)

        sidebar = QFrame()
        sidebar.setObjectName("sidebar")
        sidebar.setFixedWidth(190)
        rail = QVBoxLayout(sidebar)
        rail.setContentsMargins(18, 30, 18, 22)
        rail.setSpacing(8)
        brand = QHBoxLayout()
        brand.setSpacing(11)
        logo = symbol_label("wave", 25, "#ffffff")
        logo.setObjectName("logoDisc")
        logo.setFixedSize(44, 44)
        brand.addWidget(logo)
        names = QVBoxLayout()
        names.setSpacing(1)
        names.addWidget(label("声语", "brand"))
        names.addWidget(label("PHRASE LAB", "eyebrow"))
        brand.addLayout(names)
        rail.addLayout(brand)
        rail.addSpacing(36)
        rail.addWidget(label("工作空间", "subtle"))
        rail.addSpacing(8)
        self.nav_buttons = []
        for index, (title, symbol) in enumerate((("识别工作台", "grid"), ("短语库", "phrases"), ("设置", "settings"))):
            nav = button("  " + title, lambda checked=False, i=index: self.navigate(i), symbol=symbol, kind="nav")
            nav.setCheckable(True)
            nav.setMinimumHeight(46)
            nav.setIconSize(QSize(19, 19))
            rail.addWidget(nav)
            self.nav_buttons.append(nav)
        rail.addStretch()
        privacy, privacy_layout = card("softPanel", 14)
        privacy_layout.setSpacing(8)
        row = QHBoxLayout()
        row.addWidget(symbol_label("shield", 17, "#6882b5"))
        row.addWidget(label("本地处理", "fieldLabel"))
        row.addStretch()
        privacy_layout.addLayout(row)
        privacy_layout.addWidget(label("识别与播报在本机完成\n音频无需上传", "subtle", True))
        rail.addWidget(privacy)
        rail.addSpacing(12)
        rail.addWidget(label("信号处理实验 03", "subtle"))
        outer.addWidget(sidebar)

        content = QVBoxLayout()
        content.setContentsMargins(0, 0, 0, 0)
        content.setSpacing(0)
        outer.addLayout(content, 1)
        header = QWidget()
        header_layout = QHBoxLayout(header)
        header_layout.setContentsMargins(28, 26, 28, 22)
        titles = QVBoxLayout()
        titles.setSpacing(5)
        self.page_title = label("", "pageTitle")
        self.page_subtitle = label("", "subtle")
        titles.addWidget(self.page_title)
        titles.addWidget(self.page_subtitle)
        header_layout.addLayout(titles, 1)
        self.session_badge = badge("●  待机")
        header_layout.addWidget(self.session_badge, 0, Qt.AlignmentFlag.AlignTop)
        content.addWidget(header)

        self.pages = QStackedWidget()
        content.addWidget(self.pages, 1)
        self.pages.addWidget(self.create_workspace_page())
        self.pages.addWidget(self.create_library_page())
        self.pages.addWidget(self.create_preferences_page())

        footer = QFrame()
        footer.setObjectName("footer")
        footer_layout = QHBoxLayout(footer)
        footer_layout.setContentsMargins(28, 11, 28, 11)
        self.message = label(self.settings_problem or "就绪。选择识别模式，点击开始监听。", "subtle", True)
        footer_layout.addWidget(self.message, 1)
        self.footer_status = label("未连接麦克风", "subtle")
        footer_layout.addWidget(self.footer_status)
        content.addWidget(footer)
        self.navigate(0)

    def create_workspace_page(self):
        body = QWidget()
        layout = QVBoxLayout(body)
        layout.setContentsMargins(28, 0, 28, 24)
        layout.setSpacing(20)
        top = QHBoxLayout()
        top.setSpacing(20)
        result_card, result_layout = card("resultCard", 24)
        result_card.setMinimumWidth(360)
        result_card.setMinimumHeight(344)
        result_card.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        result_heading = QHBoxLayout()
        result_heading.addWidget(label("当前识别结果", "fieldLabel"))
        result_heading.addStretch()
        self.mode_badge = badge("实验口令", "blue")
        result_heading.addWidget(self.mode_badge)
        result_layout.addLayout(result_heading)
        result_layout.addStretch(1)
        disc = symbol_label("mic", 29, "#5b82df")
        disc.setObjectName("micDisc")
        disc.setFixedSize(72, 72)
        result_layout.addWidget(disc, 0, Qt.AlignmentFlag.AlignHCenter)
        self.result_text = label("准备好，听你说", "result", True)
        self.result_text.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.result_text.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        self.result_text.setMinimumHeight(45)
        self.result_text.setSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        result_layout.addWidget(self.result_text)
        self.result_hint = label("开始监听后，识别文字会显示在这里", "subtle", True)
        self.result_hint.setAlignment(Qt.AlignmentFlag.AlignCenter)
        result_layout.addWidget(self.result_hint)
        result_layout.addStretch(1)
        result_layout.addWidget(divider())
        metrics = QHBoxLayout()
        self.result_engine = label("等待识别", "metric")
        self.result_score = label("—", "metric")
        self.result_time = label("—", "metric")
        for title, value, tip in (
            ("识别来源", self.result_engine, "当前结果使用的识别模式"),
            ("模型得分", self.result_score, "模型得分不等于准确率；部分模型不提供该值"),
            ("计算耗时", self.result_time, "仅为模型处理耗时，不包含收音和播报时间"),
        ):
            metric = QVBoxLayout()
            metric.setSpacing(7)
            caption = label(title, "subtle")
            caption.setToolTip(tip)
            value.setToolTip(tip)
            metric.addWidget(caption)
            metric.addWidget(value)
            metrics.addLayout(metric, 1)
        result_layout.addLayout(metrics)
        top.addWidget(result_card, 1)

        controls, control_layout = card(margins=22)
        controls.setFixedWidth(300)
        control_layout.setSpacing(10)
        control_layout.addWidget(label("监听与播报", "sectionTitle"))
        control_layout.addWidget(label("识别模式", "fieldLabel"))
        self.mode = QComboBox()
        self.mode.addItem("实验口令 · 英文", "experiment")
        self.mode.addItem("自定义短语 · 中英文", "custom")
        self.mode.setCurrentIndex(0 if self.settings.mode == "experiment" else 1)
        self.mode.currentIndexChanged.connect(self.mode_changed)
        control_layout.addWidget(self.mode)
        control_layout.addWidget(label("输入设备", "fieldLabel"))
        device_row = QHBoxLayout()
        device_row.setSpacing(8)
        self.device = QComboBox()
        self.device.setMinimumWidth(0)
        self.device.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        self.device.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
        self.device.setMinimumContentsLength(8)
        self.device.addItem("系统默认麦克风", -1)
        if self.settings.input_device >= 0:
            self.device.addItem(f"已保存设备 #{self.settings.input_device}", self.settings.input_device)
            self.device.setCurrentIndex(1)
        device_row.addWidget(self.device, 1)
        self.refresh_devices_button = button("", self.refresh_devices, symbol="refresh")
        self.refresh_devices_button.setFixedSize(38, 38)
        self.refresh_devices_button.setToolTip("刷新输入设备")
        self.refresh_devices_button.setAccessibleName("刷新输入设备")
        device_row.addWidget(self.refresh_devices_button)
        control_layout.addLayout(device_row)
        control_layout.addSpacing(1)
        actions = QHBoxLayout()
        actions.setSpacing(8)
        self.start_button = button("开始监听", self.start_listening, True, "mic")
        self.start_button.setMinimumHeight(43)
        self.stop_button = button("停止", self.stop_all, symbol="stop")
        self.stop_button.setMinimumHeight(43)
        actions.addWidget(self.start_button, 1)
        actions.addWidget(self.stop_button)
        control_layout.addLayout(actions)
        control_layout.addWidget(divider())
        self.autospeak = QCheckBox("识别后自动播报")
        self.autospeak.setCursor(Qt.CursorShape.PointingHandCursor)
        self.autospeak.toggled.connect(self.auto_speech_changed)
        control_layout.addWidget(self.autospeak)
        control_layout.addWidget(label("用合成声音朗读结果。播报时暂停收音，结束后继续。", "subtle", True))
        control_layout.addStretch()
        top.addWidget(controls)
        layout.addLayout(top)

        listening, listening_layout = card(margins=16)
        row = QHBoxLayout()
        row.setSpacing(12)
        row.addWidget(symbol_label("wave", 19, "#8a9db9"))
        self.state_text = label("待机 · 点击开始监听后接入麦克风", "subtle")
        row.addWidget(self.state_text, 1)
        row.addWidget(label("输入电平", "subtle"))
        self.meter = QProgressBar()
        self.meter.setRange(0, 100)
        self.meter.setValue(0)
        self.meter.setTextVisible(False)
        self.meter.setFixedWidth(100)
        self.meter.setToolTip("来自实际输入的电平；待机时不采集音频")
        row.addWidget(self.meter)
        listening_layout.addLayout(row)
        layout.addWidget(listening)

        history, history_layout = card(margins=20)
        history.setMinimumHeight(258)
        history_heading = QHBoxLayout()
        history_heading.addWidget(label("本次会话", "sectionTitle"))
        self.history_count = badge("0 条记录")
        history_heading.addWidget(self.history_count)
        history_heading.addStretch()
        self.export_history_button = button("导出", self.export_history, symbol="download", kind="quiet")
        self.clear_history_button = button("清空", self.clear_history, kind="quiet")
        history_heading.addWidget(self.export_history_button)
        history_heading.addWidget(self.clear_history_button)
        history_layout.addLayout(history_heading)
        self.history_table = table(["时间", "识别文字", "模型得分", "计算耗时"])
        self.history_table.setColumnWidth(0, 116)
        self.history_table.setColumnWidth(2, 94)
        self.history_table.setColumnWidth(3, 108)
        self.history_table.itemSelectionChanged.connect(self.update_history_actions)
        self.history_table.setMinimumHeight(130)
        self.history_stack = QStackedWidget()
        self.history_stack.addWidget(empty_state("还没有识别记录", "开始监听后，识别到的短语会显示在这里"))
        self.history_stack.addWidget(self.history_table)
        history_layout.addWidget(self.history_stack, 1)
        history_footer = QHBoxLayout()
        self.replay_button = button("朗读所选结果", self.replay, symbol="speaker", kind="quiet")
        self.replay_button.setToolTip("根据所选文字合成新语音，会从扬声器出声")
        history_footer.addWidget(self.replay_button)
        history_footer.addStretch()
        history_footer.addWidget(label("记录仅保留在当前会话", "subtle"))
        history_layout.addLayout(history_footer)
        layout.addWidget(history, 1)
        return scroll_page(body)

    def create_library_page(self):
        body = QWidget()
        page = QVBoxLayout(body)
        page.setContentsMargins(28, 0, 28, 24)
        page.setSpacing(16)
        self.library_note = label("", "subtle", True)
        page.addWidget(self.library_note)
        self.phrase_editor, layout = card(margins=24)
        page.addWidget(self.phrase_editor, 1)
        heading = QHBoxLayout()
        heading.addWidget(label("我的短语", "sectionTitle"))
        self.phrase_count = badge("0 条启用", "blue")
        heading.addWidget(self.phrase_count)
        heading.addStretch()
        self.add_phrase_button = button("添加短语", self.add_phrase, True, "plus")
        heading.addWidget(self.add_phrase_button)
        layout.addLayout(heading)
        toolbar = QHBoxLayout()
        toolbar.setSpacing(8)
        self.phrase_search = QLineEdit()
        self.phrase_search.setObjectName("search")
        self.phrase_search.setPlaceholderText("搜索短语…")
        self.phrase_search.setClearButtonEnabled(True)
        self.phrase_search.setMinimumWidth(160)
        self.phrase_search.addAction(icon("search"), QLineEdit.ActionPosition.LeadingPosition)
        self.phrase_search.textChanged.connect(self.filter_phrases)
        toolbar.addWidget(self.phrase_search, 1)
        toolbar.addWidget(button("导入", self.import_phrases, symbol="upload", kind="quiet"))
        toolbar.addWidget(button("导出", self.export_phrases, symbol="download", kind="quiet"))
        layout.addLayout(toolbar)
        self.phrase_table = table(["启用", "识别短语", "发音设置"])
        self.phrase_table.setColumnWidth(0, 76)
        self.phrase_table.setColumnWidth(2, 135)
        self.phrase_table.setMinimumHeight(270)
        self.phrase_table.itemChanged.connect(self.phrase_toggled)
        self.phrase_table.itemSelectionChanged.connect(self.update_phrase_actions)
        self.phrase_table.cellDoubleClicked.connect(lambda row, col: self.edit_phrase() if col != 0 else None)
        self.phrase_stack = QStackedWidget()
        self.phrase_stack.addWidget(self.phrase_table)
        self.phrase_empty = empty_state("没有找到短语", "试试其他搜索词，或添加一条新短语。", "phrases")
        self.phrase_stack.addWidget(self.phrase_empty)
        layout.addWidget(self.phrase_stack, 1)
        actions = QHBoxLayout()
        self.edit_phrase_button = button("编辑", self.edit_phrase, symbol="edit")
        self.delete_phrase_button = button("删除", self.delete_phrase, symbol="trash", kind="danger")
        actions.addWidget(self.edit_phrase_button)
        actions.addWidget(self.delete_phrase_button)
        actions.addStretch()
        actions.addWidget(button("检查发音配置", self.check_keywords, symbol="check", kind="quiet"))
        layout.addLayout(actions)
        layout.addWidget(divider())
        layout.addWidget(label("支持中文和英文。先停止监听，再添加或修改短语；保存后手动开始监听。", "subtle", True))
        return scroll_page(body)

    def create_preferences_page(self):
        body = QWidget()
        page = QVBoxLayout(body)
        page.setContentsMargins(28, 0, 28, 24)
        page.setSpacing(18)
        self.settings_lock_note = label("停止监听后可修改设置，下次开始监听时生效。", "subtle", True)
        page.addWidget(self.settings_lock_note)
        self.settings_editor = QWidget()
        editor = QVBoxLayout(self.settings_editor)
        editor.setContentsMargins(0, 0, 0, 0)
        editor.setSpacing(18)
        page.addWidget(self.settings_editor)
        row = QHBoxLayout()
        row.setSpacing(18)
        detection, detection_layout = card(margins=24)
        detection_layout.addWidget(label("识别参数", "sectionTitle"))
        detection_layout.addWidget(label("平衡响应灵敏度与误触发。", "subtle", True))
        self.exp_threshold = QDoubleSpinBox()
        self.exp_threshold.setRange(0.05, 0.99)
        self.exp_threshold.setSingleStep(0.05)
        self.exp_threshold.setValue(self.settings.threshold)
        self.kws_threshold = QDoubleSpinBox()
        self.kws_threshold.setRange(0.05, 0.99)
        self.kws_threshold.setSingleStep(0.05)
        self.kws_threshold.setValue(self.settings.custom_threshold)
        self.rms_threshold = QDoubleSpinBox()
        self.rms_threshold.setDecimals(4)
        self.rms_threshold.setRange(0.0001, 0.2)
        self.rms_threshold.setSingleStep(0.001)
        self.rms_threshold.setValue(self.settings.rms_threshold)
        for title, control in (("实验识别阈值", self.exp_threshold), ("自定义触发阈值", self.kws_threshold), ("有声电平阈值（RMS）", self.rms_threshold)):
            self.setting_row(detection_layout, title, control)
        detection_layout.addWidget(label("识别阈值越高，通常越不容易触发。可结合实际录音调整，过高可能增加漏识别。", "subtle", True))
        detection_layout.addWidget(label("有声电平阈值决定多轻的声音可以触发识别。轻声或短口令容易漏掉时可适当降低；环境嘈杂时可适当提高。", "subtle", True))
        row.addWidget(detection, 1)
        speech, speech_layout = card(margins=24)
        speech_layout.addWidget(label("合成播报", "sectionTitle"))
        speech_layout.addWidget(label("根据识别文字，生成新的语音。", "subtle", True))
        self.volume = QSpinBox()
        self.volume.setRange(0, 100)
        self.volume.setSuffix(" %")
        self.volume.setValue(self.settings.volume)
        self.rate = QSpinBox()
        self.rate.setRange(-5, 5)
        self.rate.setValue(self.settings.rate)
        self.setting_row(speech_layout, "合成音量", self.volume)
        self.setting_row(speech_layout, "合成语速", self.rate)
        speech_layout.addWidget(label("语速 0 为默认，负值更慢，正值更快。", "subtle", True))
        speech_layout.addStretch()
        speech_layout.addWidget(label("自动播报每次启动默认关闭，可在识别工作台开启。", "subtle", True))
        row.addWidget(speech, 1)
        editor.addLayout(row)
        save_row = QHBoxLayout()
        save_row.addWidget(label("所有设置保存在本机。", "subtle"))
        save_row.addStretch()
        self.save_settings_button = button("保存设置", self.save_from_ui, True, "check")
        save_row.addWidget(self.save_settings_button)
        editor.addLayout(save_row)
        model_card, model_layout = card(margins=24)
        model_heading = QHBoxLayout()
        model_heading.addWidget(label("模型与运行环境", "sectionTitle"))
        model_heading.addStretch()
        model_heading.addWidget(button("刷新", self.update_model_status, symbol="refresh", kind="quiet"))
        model_layout.addLayout(model_heading)
        self.native_badge = badge("待检查")
        self.custom_badge = badge("待检查")
        for title, detail, state in (
            ("实验口令", "Log-Mel + BC-ResNet · 10 个英文口令及静音 / 未知", self.native_badge),
            ("自定义短语", "Zipformer · 本地中英文关键词识别", self.custom_badge),
        ):
            line = QHBoxLayout()
            description = QVBoxLayout()
            description.setSpacing(5)
            description.addWidget(label(title))
            description.addWidget(label(detail, "subtle", True))
            line.addLayout(description, 1)
            line.addWidget(state)
            model_layout.addLayout(line)
        model_layout.addWidget(divider())
        model_layout.addWidget(label("实验口令：down · go · left · no · off · on · right · stop · up · yes", "subtle", True))
        self.model_status = label("", "subtle", True)
        model_layout.addWidget(self.model_status)
        page.addWidget(model_card)
        page.addStretch()
        return scroll_page(body)

    @staticmethod
    def setting_row(layout, title, control):
        row = QHBoxLayout()
        row.setSpacing(12)
        row.addWidget(label(title, "fieldLabel"), 1)
        control.setFixedWidth(112)
        row.addWidget(control)
        layout.addLayout(row)

    def navigate(self, index):
        self.pages.setCurrentIndex(index)
        title, subtitle = PAGE_TITLES[index]
        self.page_title.setText(title)
        self.page_subtitle.setText(subtitle)
        for i, (nav, symbol) in enumerate(zip(self.nav_buttons, ("grid", "phrases", "settings"))):
            nav.setChecked(i == index)
            nav.setIcon(icon(symbol, "#3567e8" if i == index else "#8392aa"))
